services:
  user:
    restart: unless-stopped
    build: ./Services/User/IW
    ports:
      - 32770:80
      - 32771:403
    depends_on:
      - rabbitmq

  order:
    restart: unless-stopped
    build: ./Services/Order/IW
    ports:
      - 32772:80
      - 32773:403
    depends_on:
      - rabbitmq

  product:
    restart: unless-stopped
    build: ./Services/Product/IW
    ports:
      - 32774:80
      - 32775:403
    depends_on:
      - rabbitmq

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - 5433:5432

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass yourpassword

  inventory:
    restart: unless-stopped
    build: ./Services/Inventory/IW
    ports:
      - 32776:80
      - 32777:403
    depends_on:
      rabbitmq:
        condition: service_healthy

  cart:
    restart: unless-stopped
    build: ./Services/Cart/IW
    ports:
      - 32778:80
      - 32779:403
    depends_on:
      - rabbitmq

  payment:
    restart: unless-stopped
    build: ./Services/Payment/IW
    ports:
      - 32780:80
      - 32781:403
    depends_on:
      - rabbitmq

  graphql-engine:
    image: hasura/graphql-engine:v2.33.0.cli-migrations-v3
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://data-connector-agent:8081/api/v1/athena"},"mariadb":{"uri":"http://data-connector-agent:8081/api/v1/mariadb"},"mysql8":{"uri":"http://data-connector-agent:8081/api/v1/mysql"},"oracle":{"uri":"http://data-connector-agent:8081/api/v1/oracle"},"snowflake":{"uri":"http://data-connector-agent:8081/api/v1/snowflake"}}}}'
    depends_on:
      - user
      - product
      - order
      - inventory
      - cart
      - data-connector-agent
      - payment
      - rabbitmq

  data-connector-agent:
    image: hasura/graphql-data-connector:v2.33.0
    restart: always
    ports:
      - 8081:8081
    environment:
      QUARKUS_LOG_LEVEL: ERROR
      QUARKUS_OPENTELEMETRY_ENABLED: "false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/athena/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  dotnet-sdk:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - postgres
    tty: true
    entrypoint: /bin/bash -c "dotnet tool install --global dotnet-ef --version 6.* && export PATH=\$PATH:\$HOME/.dotnet/tools && /bin/bash"

  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      # RABBITMQ_DEFAULT_VHOST: ubmtzzec
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  db_data:
